services:
  app:
    build: .
    container_name: lector_manga_app
    ports:
      - "3000:3000"
    volumes:
      - /home/devcode/mangas-temp:/app/Manga:ro
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mangadb
    depends_on:
      mongodb:
        condition: service_healthy
    command: npm run dev
    networks:
      - lector_manga_network


  mongodb:
    image: mongo:latest
    container_name: lector_manga_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mangadb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
        - lector_manga_network



volumes:
  mongodb_data:



networks:
  lector_manga_network:
    driver: bridge
