services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - /home/devcode/mangas-temp:/app/Manga:ro
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/mangadb
    depends_on:
      mongodb:
        condition: service_healthy
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - /home/dev/Documents/MongoDB:/data/db
    environment:
      - MONGO_INITDB_DATABASE=mangadb
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
